name: iOS client build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  XCODE_PROJECT_DIR: ./Clients/iOS/FitWithFriends
  WORKSPACE_NAME: FitWithFriends.xcworkspace

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          scheme: ${{ 'FitWithFriends' }}
          platform: ${{ 'iOS Simulator' }}
        working-directory: ${{ env.XCODE_PROJECT_DIR }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild build-for-testing -scheme "$scheme" -workspace $WORKSPACE_NAME -destination "platform=$platform,name=$device"
      - name: Test
        env:
          scheme: ${{ 'FitWithFriends' }}
          platform: ${{ 'iOS Simulator' }}
        working-directory: ${{ env.XCODE_PROJECT_DIR }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild test-without-building -scheme "$scheme" -workspace $WORKSPACE_NAME -destination "platform=$platform,name=$device"
