version: '3.8'
services:

  node-app:
    build:
      context: ./FitWithFriends
    ports:
      - '3000:3000'
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
      - PGUSESSL=0
      - FWF_AUTH_USE_LOCAL_KEYPAIR=1
      - FWF_AUTH_PRIVATE_KEY_PATH=TestCerts/fwftest-key.pem
      - FWF_AUTH_PUBLIC_KEY_PATH=TestCerts/fwftest.pem
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - ./CreateDatabaseTables.sql:/docker-entrypoint-initdb.d/1_CreateDatabaseTables.sql
      - ./SetupTestData.sql:/docker-entrypoint-initdb.d/2_SetupTestData.sql
